// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/crosbymichael/boss/api/v1/boss.proto

package v1 // import "github.com/crosbymichael/boss/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// skipping weak import gogoproto "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{1}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{3}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type KillRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Signal               uint32   `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{4}
}
func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (dst *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(dst, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

func (m *KillRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *KillRequest) GetSignal() uint32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{5}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Containers           []*ListContainer `protobuf:"bytes,1,rep,name=containers" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{6}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetContainers() []*ListContainer {
	if m != nil {
		return m.Containers
	}
	return nil
}

type ListContainer struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	IP                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Cpu                  uint64   `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryUsage          float64  `protobuf:"fixed64,6,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit          float64  `protobuf:"fixed64,7,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	PidUsage             uint64   `protobuf:"varint,8,opt,name=pid_usage,json=pidUsage,proto3" json:"pid_usage,omitempty"`
	PidLimit             uint64   `protobuf:"varint,9,opt,name=pid_limit,json=pidLimit,proto3" json:"pid_limit,omitempty"`
	FsSize               int64    `protobuf:"varint,10,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContainer) Reset()         { *m = ListContainer{} }
func (m *ListContainer) String() string { return proto.CompactTextString(m) }
func (*ListContainer) ProtoMessage()    {}
func (*ListContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{7}
}
func (m *ListContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContainer.Unmarshal(m, b)
}
func (m *ListContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContainer.Marshal(b, m, deterministic)
}
func (dst *ListContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContainer.Merge(dst, src)
}
func (m *ListContainer) XXX_Size() int {
	return xxx_messageInfo_ListContainer.Size(m)
}
func (m *ListContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContainer.DiscardUnknown(m)
}

var xxx_messageInfo_ListContainer proto.InternalMessageInfo

func (m *ListContainer) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ListContainer) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ListContainer) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListContainer) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *ListContainer) GetCpu() uint64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *ListContainer) GetMemoryUsage() float64 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *ListContainer) GetMemoryLimit() float64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *ListContainer) GetPidUsage() uint64 {
	if m != nil {
		return m.PidUsage
	}
	return 0
}

func (m *ListContainer) GetPidLimit() uint64 {
	if m != nil {
		return m.PidLimit
	}
	return 0
}

func (m *ListContainer) GetFsSize() int64 {
	if m != nil {
		return m.FsSize
	}
	return 0
}

type RollbackRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollbackRequest) Reset()         { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()    {}
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{8}
}
func (m *RollbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackRequest.Unmarshal(m, b)
}
func (m *RollbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackRequest.Marshal(b, m, deterministic)
}
func (dst *RollbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackRequest.Merge(dst, src)
}
func (m *RollbackRequest) XXX_Size() int {
	return xxx_messageInfo_RollbackRequest.Size(m)
}
func (m *RollbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackRequest proto.InternalMessageInfo

func (m *RollbackRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type RollbackResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RollbackResponse) Reset()         { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()    {}
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{9}
}
func (m *RollbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackResponse.Unmarshal(m, b)
}
func (m *RollbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackResponse.Marshal(b, m, deterministic)
}
func (dst *RollbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackResponse.Merge(dst, src)
}
func (m *RollbackResponse) XXX_Size() int {
	return xxx_messageInfo_RollbackResponse.Size(m)
}
func (m *RollbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackResponse proto.InternalMessageInfo

func (m *RollbackResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type StartRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{10}
}
func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (dst *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(dst, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type StopRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{11}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type UpdateRequest struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{12}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type UpdateResponse struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{13}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type PushBuildRequest struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushBuildRequest) Reset()         { *m = PushBuildRequest{} }
func (m *PushBuildRequest) String() string { return proto.CompactTextString(m) }
func (*PushBuildRequest) ProtoMessage()    {}
func (*PushBuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{14}
}
func (m *PushBuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushBuildRequest.Unmarshal(m, b)
}
func (m *PushBuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushBuildRequest.Marshal(b, m, deterministic)
}
func (dst *PushBuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushBuildRequest.Merge(dst, src)
}
func (m *PushBuildRequest) XXX_Size() int {
	return xxx_messageInfo_PushBuildRequest.Size(m)
}
func (m *PushBuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushBuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushBuildRequest proto.InternalMessageInfo

func (m *PushBuildRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Container struct {
	ID                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image                string              `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Network              string              `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Process              *Process            `protobuf:"bytes,4,opt,name=process" json:"process,omitempty"`
	Mounts               []*Mount            `protobuf:"bytes,5,rep,name=mounts" json:"mounts,omitempty"`
	Resources            *Resources          `protobuf:"bytes,6,opt,name=resources" json:"resources,omitempty"`
	Gpus                 *GPUs               `protobuf:"bytes,7,opt,name=gpus" json:"gpus,omitempty"`
	Services             map[string]*Service `protobuf:"bytes,8,rep,name=services" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Configs              map[string]*Config  `protobuf:"bytes,9,rep,name=configs" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{15}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Container) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Container) GetProcess() *Process {
	if m != nil {
		return m.Process
	}
	return nil
}

func (m *Container) GetMounts() []*Mount {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *Container) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Container) GetGpus() *GPUs {
	if m != nil {
		return m.Gpus
	}
	return nil
}

func (m *Container) GetServices() map[string]*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Container) GetConfigs() map[string]*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type Config struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Signal               string   `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{16}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Config) GetSignal() string {
	if m != nil {
		return m.Signal
	}
	return ""
}

func (m *Config) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Service struct {
	Port                 int64        `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Labels               []string     `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty"`
	Url                  string       `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Check                *HealthCheck `protobuf:"bytes,4,opt,name=check" json:"check,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{17}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Service) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Service) GetCheck() *HealthCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

type HealthCheck struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Interval             int64    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{18}
}
func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (dst *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(dst, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *HealthCheck) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *HealthCheck) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *HealthCheck) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type GPUs struct {
	Devices              []int64  `protobuf:"varint,1,rep,packed,name=devices" json:"devices,omitempty"`
	Capabilities         []string `protobuf:"bytes,2,rep,name=capabilities" json:"capabilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GPUs) Reset()         { *m = GPUs{} }
func (m *GPUs) String() string { return proto.CompactTextString(m) }
func (*GPUs) ProtoMessage()    {}
func (*GPUs) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{19}
}
func (m *GPUs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GPUs.Unmarshal(m, b)
}
func (m *GPUs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GPUs.Marshal(b, m, deterministic)
}
func (dst *GPUs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GPUs.Merge(dst, src)
}
func (m *GPUs) XXX_Size() int {
	return xxx_messageInfo_GPUs.Size(m)
}
func (m *GPUs) XXX_DiscardUnknown() {
	xxx_messageInfo_GPUs.DiscardUnknown(m)
}

var xxx_messageInfo_GPUs proto.InternalMessageInfo

func (m *GPUs) GetDevices() []int64 {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *GPUs) GetCapabilities() []string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

type Resources struct {
	Cpus                 float64  `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	Memory               int64    `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Score                int64    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	NoFile               uint64   `protobuf:"varint,4,opt,name=no_file,json=noFile,proto3" json:"no_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{20}
}
func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (dst *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(dst, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetCpus() float64 {
	if m != nil {
		return m.Cpus
	}
	return 0
}

func (m *Resources) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Resources) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Resources) GetNoFile() uint64 {
	if m != nil {
		return m.NoFile
	}
	return 0
}

type Mount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Options              []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mount) Reset()         { *m = Mount{} }
func (m *Mount) String() string { return proto.CompactTextString(m) }
func (*Mount) ProtoMessage()    {}
func (*Mount) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{21}
}
func (m *Mount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mount.Unmarshal(m, b)
}
func (m *Mount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mount.Marshal(b, m, deterministic)
}
func (dst *Mount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mount.Merge(dst, src)
}
func (m *Mount) XXX_Size() int {
	return xxx_messageInfo_Mount.Size(m)
}
func (m *Mount) XXX_DiscardUnknown() {
	xxx_messageInfo_Mount.DiscardUnknown(m)
}

var xxx_messageInfo_Mount proto.InternalMessageInfo

func (m *Mount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Mount) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Mount) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Mount) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

type Process struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Env                  []string `protobuf:"bytes,3,rep,name=env" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{22}
}
func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (dst *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(dst, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Process) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Process) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type User struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_boss_685bf8a460723ffb, []int{23}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "io.boss.v1.CreateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "io.boss.v1.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "io.boss.v1.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "io.boss.v1.GetResponse")
	proto.RegisterType((*KillRequest)(nil), "io.boss.v1.KillRequest")
	proto.RegisterType((*ListRequest)(nil), "io.boss.v1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "io.boss.v1.ListResponse")
	proto.RegisterType((*ListContainer)(nil), "io.boss.v1.ListContainer")
	proto.RegisterType((*RollbackRequest)(nil), "io.boss.v1.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "io.boss.v1.RollbackResponse")
	proto.RegisterType((*StartRequest)(nil), "io.boss.v1.StartRequest")
	proto.RegisterType((*StopRequest)(nil), "io.boss.v1.StopRequest")
	proto.RegisterType((*UpdateRequest)(nil), "io.boss.v1.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "io.boss.v1.UpdateResponse")
	proto.RegisterType((*PushBuildRequest)(nil), "io.boss.v1.PushBuildRequest")
	proto.RegisterType((*Container)(nil), "io.boss.v1.Container")
	proto.RegisterMapType((map[string]*Config)(nil), "io.boss.v1.Container.ConfigsEntry")
	proto.RegisterMapType((map[string]*Service)(nil), "io.boss.v1.Container.ServicesEntry")
	proto.RegisterType((*Config)(nil), "io.boss.v1.Config")
	proto.RegisterType((*Service)(nil), "io.boss.v1.Service")
	proto.RegisterType((*HealthCheck)(nil), "io.boss.v1.HealthCheck")
	proto.RegisterType((*GPUs)(nil), "io.boss.v1.GPUs")
	proto.RegisterType((*Resources)(nil), "io.boss.v1.Resources")
	proto.RegisterType((*Mount)(nil), "io.boss.v1.Mount")
	proto.RegisterType((*Process)(nil), "io.boss.v1.Process")
	proto.RegisterType((*User)(nil), "io.boss.v1.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*types.Empty, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	PushBuild(ctx context.Context, in *PushBuildRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PushBuild(ctx context.Context, in *PushBuildRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/io.boss.v1.Agent/PushBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Create(context.Context, *CreateRequest) (*types.Empty, error)
	Delete(context.Context, *DeleteRequest) (*types.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Kill(context.Context, *KillRequest) (*types.Empty, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	Start(context.Context, *StartRequest) (*types.Empty, error)
	Stop(context.Context, *StopRequest) (*types.Empty, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	PushBuild(context.Context, *PushBuildRequest) (*types.Empty, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PushBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PushBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.boss.v1.Agent/PushBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PushBuild(ctx, req.(*PushBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.boss.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Agent_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Agent_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Agent_Get_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Agent_Kill_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Agent_List_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Agent_Rollback_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Agent_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Agent_Stop_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Agent_Update_Handler,
		},
		{
			MethodName: "PushBuild",
			Handler:    _Agent_PushBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/crosbymichael/boss/api/v1/boss.proto",
}

func init() {
	proto.RegisterFile("github.com/crosbymichael/boss/api/v1/boss.proto", fileDescriptor_boss_685bf8a460723ffb)
}

var fileDescriptor_boss_685bf8a460723ffb = []byte{
	// 1173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x6d, 0x8f, 0xdb, 0xc4,
	0x13, 0xff, 0x27, 0x76, 0x92, 0xcb, 0xe4, 0xf2, 0xe7, 0x58, 0xca, 0xd5, 0xa4, 0x48, 0x04, 0x53,
	0x68, 0x0e, 0xa9, 0x89, 0x7a, 0x95, 0x28, 0xa5, 0xa0, 0xaa, 0xf7, 0xc0, 0x51, 0x51, 0xd0, 0x69,
	0x4f, 0x27, 0x21, 0xde, 0x54, 0x8e, 0xb3, 0x71, 0x56, 0xe7, 0x78, 0x8d, 0x77, 0x1d, 0x94, 0x7e,
	0x12, 0xbe, 0x02, 0x5f, 0x8a, 0x17, 0xbc, 0xe6, 0x43, 0xa0, 0xd9, 0x5d, 0x27, 0xf6, 0x35, 0xd1,
	0xa1, 0xde, 0xbb, 0x79, 0x9e, 0xdf, 0xae, 0x67, 0x67, 0xc6, 0x30, 0x8a, 0xb8, 0x9a, 0xe5, 0xe3,
	0x61, 0x28, 0xe6, 0xa3, 0x30, 0x13, 0x72, 0xbc, 0x9c, 0xf3, 0x70, 0x16, 0xb0, 0x78, 0x34, 0x16,
	0x52, 0x8e, 0x82, 0x94, 0x8f, 0x16, 0x8f, 0x34, 0x3d, 0x4c, 0x33, 0xa1, 0x04, 0x01, 0x2e, 0x86,
	0x9a, 0x5d, 0x3c, 0xea, 0xdd, 0x89, 0x44, 0x24, 0xb4, 0x78, 0x84, 0x94, 0xb1, 0xe8, 0xdd, 0x8b,
	0x84, 0x88, 0x62, 0x36, 0xd2, 0xdc, 0x38, 0x9f, 0x8e, 0xd8, 0x3c, 0x55, 0x4b, 0xa3, 0xf4, 0x4f,
	0xa0, 0x7b, 0x9c, 0xb1, 0x40, 0x31, 0xca, 0x7e, 0xcb, 0x99, 0x54, 0xe4, 0x31, 0xb4, 0x43, 0x91,
	0xa8, 0x80, 0x27, 0x2c, 0xf3, 0x6a, 0xfd, 0xda, 0xa0, 0x73, 0xf8, 0xe1, 0x70, 0x9d, 0x63, 0x78,
	0x5c, 0x28, 0xe9, 0xda, 0xce, 0x7f, 0x00, 0xdd, 0x13, 0x16, 0xb3, 0x75, 0x94, 0x7d, 0xa8, 0xf3,
	0x89, 0x76, 0x6f, 0x1f, 0x35, 0xff, 0xfe, 0xeb, 0x93, 0xfa, 0xcb, 0x13, 0x5a, 0xe7, 0x13, 0xff,
	0x3e, 0xc0, 0x19, 0x53, 0x37, 0x59, 0x1d, 0x41, 0x47, 0x5b, 0xc9, 0x54, 0x24, 0x92, 0xbd, 0x1b,
	0xa4, 0xef, 0xa0, 0xf3, 0x23, 0x8f, 0xe3, 0x1b, 0x52, 0x91, 0x7d, 0x68, 0x4a, 0x1e, 0x25, 0x41,
	0xec, 0xd5, 0xfb, 0xb5, 0x41, 0x97, 0x5a, 0xce, 0xef, 0x42, 0xe7, 0x15, 0x97, 0x05, 0x52, 0xff,
	0x25, 0xec, 0x1a, 0xd6, 0x42, 0x7a, 0x0a, 0xb0, 0x4a, 0x25, 0xbd, 0x5a, 0xdf, 0x19, 0x74, 0x0e,
	0x3f, 0x2a, 0x63, 0x42, 0xeb, 0x35, 0xae, 0x92, 0xb1, 0xff, 0x47, 0x1d, 0xba, 0x15, 0xed, 0x56,
	0x6c, 0x77, 0xa0, 0xc1, 0xe7, 0x41, 0xc4, 0x34, 0xb4, 0x36, 0x35, 0x8c, 0x46, 0xac, 0x02, 0x95,
	0x4b, 0xcf, 0xd1, 0x62, 0xcb, 0xe9, 0x28, 0xa9, 0xe7, 0x96, 0xa2, 0x9c, 0xd3, 0x3a, 0x4f, 0xc9,
	0x1e, 0x38, 0x61, 0x9a, 0x7b, 0x8d, 0x7e, 0x6d, 0xe0, 0x52, 0x24, 0xc9, 0xa7, 0xb0, 0x3b, 0x67,
	0x73, 0x91, 0x2d, 0x5f, 0xe7, 0x12, 0xc3, 0x37, 0xfb, 0xb5, 0x41, 0x8d, 0x76, 0x8c, 0xec, 0x12,
	0x45, 0x25, 0x93, 0x98, 0xcf, 0xb9, 0xf2, 0x5a, 0x65, 0x93, 0x57, 0x28, 0x22, 0xf7, 0xa0, 0x9d,
	0xf2, 0x89, 0x0d, 0xb1, 0xa3, 0xa3, 0xef, 0xa4, 0x7c, 0x62, 0xfc, 0xad, 0xd2, 0x38, 0xb7, 0x57,
	0x4a, 0xe3, 0x79, 0x17, 0x5a, 0x53, 0xf9, 0x5a, 0xf2, 0x37, 0xcc, 0x83, 0x7e, 0x6d, 0xe0, 0xd0,
	0xe6, 0x54, 0x5e, 0xf0, 0x37, 0xcc, 0x3f, 0x80, 0xf7, 0xa8, 0x88, 0xe3, 0x71, 0x10, 0x5e, 0xdd,
	0x54, 0x22, 0x67, 0xb0, 0xb7, 0x36, 0xbd, 0x4d, 0x9d, 0x7c, 0x01, 0xbb, 0x17, 0x2a, 0xc8, 0x6e,
	0xac, 0xc9, 0xcf, 0xa1, 0x73, 0xa1, 0x44, 0x7a, 0x93, 0xd9, 0x09, 0x74, 0x2f, 0xd3, 0xc9, 0x6d,
	0xdf, 0xd3, 0x29, 0xfc, 0xbf, 0x88, 0x72, 0x9b, 0xb3, 0xdd, 0x87, 0xbd, 0xf3, 0x5c, 0xce, 0x8e,
	0x72, 0x1e, 0x4f, 0x0a, 0x3c, 0x7b, 0xe0, 0x64, 0x6c, 0x6a, 0x90, 0x53, 0x24, 0xfd, 0x3f, 0x5d,
	0x68, 0xbf, 0x6b, 0x31, 0x7a, 0xd0, 0x4a, 0x98, 0xfa, 0x5d, 0x64, 0x57, 0xb6, 0x1a, 0x0b, 0x96,
	0x3c, 0x84, 0x56, 0x9a, 0x89, 0x90, 0x49, 0xa9, 0x6b, 0xb2, 0x73, 0xf8, 0x41, 0x19, 0xee, 0xb9,
	0x51, 0xd1, 0xc2, 0x86, 0x1c, 0x40, 0x73, 0x2e, 0xf2, 0x44, 0x49, 0xaf, 0xa1, 0x1f, 0xd3, 0xfb,
	0x65, 0xeb, 0x9f, 0x50, 0x43, 0xad, 0x01, 0x5e, 0x45, 0xc6, 0xa4, 0xc8, 0xb3, 0x90, 0x49, 0x5d,
	0xbb, 0xd7, 0xae, 0x82, 0x16, 0x4a, 0xba, 0xb6, 0x23, 0xf7, 0xc1, 0x8d, 0xd2, 0x5c, 0xea, 0x42,
	0xee, 0x1c, 0xee, 0x95, 0xed, 0xcf, 0xce, 0x2f, 0x25, 0xd5, 0x5a, 0xf2, 0x1c, 0x76, 0x24, 0xcb,
	0x16, 0x1c, 0x23, 0xef, 0x68, 0x1c, 0x9f, 0x6d, 0xbc, 0xe4, 0xe1, 0x85, 0xb5, 0x3a, 0x4d, 0x54,
	0xb6, 0xa4, 0x2b, 0x27, 0xf2, 0x2d, 0xb4, 0x42, 0x91, 0x4c, 0x79, 0x24, 0xbd, 0xb6, 0xf6, 0xf7,
	0x37, 0xfb, 0x1f, 0x1b, 0x23, 0xe3, 0x5e, 0xb8, 0xf4, 0xce, 0xa1, 0x5b, 0x09, 0x8c, 0x1f, 0xeb,
	0x8a, 0x2d, 0x8b, 0x8f, 0x75, 0xc5, 0x96, 0xe4, 0x00, 0x1a, 0x8b, 0x20, 0xce, 0xcd, 0x67, 0xb8,
	0x76, 0xa9, 0xd6, 0x97, 0x1a, 0x8b, 0x6f, 0xea, 0x5f, 0xd7, 0x7a, 0x3f, 0xc3, 0x6e, 0x39, 0xd5,
	0x86, 0x80, 0x83, 0x6a, 0x40, 0x72, 0x0d, 0xef, 0x94, 0x47, 0xa5, 0x78, 0xfe, 0x14, 0x9a, 0x46,
	0x48, 0x08, 0xb8, 0x69, 0xa0, 0x66, 0x36, 0x94, 0xa6, 0x75, 0x6b, 0xd2, 0xf7, 0x6d, 0x8b, 0xc4,
	0x72, 0xa5, 0x26, 0x5b, 0xb4, 0x2c, 0xcd, 0x61, 0xf5, 0x60, 0xb1, 0xb2, 0x44, 0x99, 0xbe, 0x45,
	0x0b, 0xd6, 0x5f, 0x40, 0xcb, 0x9e, 0x46, 0x27, 0x12, 0x99, 0xd2, 0x89, 0x1c, 0xaa, 0x69, 0x0c,
	0x18, 0x07, 0x63, 0x16, 0x4b, 0xaf, 0xde, 0x77, 0x30, 0xa0, 0xe1, 0xf0, 0x78, 0x79, 0x56, 0x64,
	0x41, 0x92, 0x3c, 0x84, 0x46, 0x38, 0x63, 0xe1, 0x95, 0x2d, 0xc2, 0xbb, 0xe5, 0xe3, 0xfd, 0xc0,
	0x82, 0x58, 0xcd, 0x8e, 0x51, 0x4d, 0x8d, 0x95, 0x2f, 0xa0, 0x53, 0x92, 0x62, 0x6e, 0xb5, 0x4c,
	0x59, 0x71, 0x48, 0xa4, 0x49, 0x0f, 0x76, 0x78, 0xa2, 0x58, 0xb6, 0xb0, 0x33, 0xc3, 0xa1, 0x2b,
	0x1e, 0x0f, 0xa4, 0xf8, 0x9c, 0x89, 0x5c, 0x69, 0x0c, 0x0e, 0x2d, 0x58, 0x44, 0x3c, 0x67, 0x6a,
	0x26, 0x26, 0xf6, 0xa4, 0x96, 0xf3, 0x4f, 0xc0, 0xc5, 0xfa, 0x43, 0xcf, 0x09, 0x33, 0x85, 0x87,
	0xd3, 0xc4, 0xa1, 0x05, 0x4b, 0x7c, 0xd8, 0x0d, 0x83, 0x34, 0x18, 0xf3, 0x98, 0x2b, 0xce, 0x8a,
	0x13, 0x57, 0x64, 0xfe, 0x14, 0xda, 0xab, 0xaa, 0x47, 0xd0, 0x21, 0x96, 0x7a, 0x4d, 0xf7, 0x6c,
	0x4d, 0x9b, 0xf4, 0xd8, 0xbb, 0x2d, 0x64, 0xcb, 0xe1, 0xab, 0x96, 0xa1, 0xc8, 0x98, 0x85, 0x6b,
	0x18, 0x6c, 0xd0, 0x89, 0x78, 0x3d, 0xe5, 0x31, 0xd3, 0x68, 0x5d, 0xda, 0x4c, 0xc4, 0xf7, 0x3c,
	0x66, 0xbe, 0x80, 0x86, 0x7e, 0x8b, 0x1b, 0x2f, 0x66, 0xdb, 0xd7, 0xef, 0x43, 0x67, 0xc2, 0xa4,
	0xe2, 0x49, 0xa0, 0xb8, 0x48, 0xec, 0xc7, 0x29, 0x8b, 0xf0, 0xf0, 0x22, 0x45, 0x0a, 0x7b, 0x05,
	0x9e, 0xae, 0x60, 0xfd, 0x4b, 0x68, 0xd9, 0x56, 0x81, 0x2f, 0x38, 0x97, 0xab, 0xe6, 0x57, 0x79,
	0xc1, 0x97, 0x92, 0x65, 0x54, 0x6b, 0x11, 0x58, 0x90, 0x45, 0xc5, 0x2d, 0x69, 0x1a, 0xab, 0x82,
	0x25, 0x0b, 0xcf, 0xd1, 0x22, 0x24, 0xfd, 0x2f, 0xc1, 0x45, 0x1f, 0x5d, 0x2f, 0xb6, 0xdb, 0x75,
	0x29, 0x92, 0x28, 0x89, 0xf8, 0xc4, 0x2e, 0x03, 0x48, 0x1e, 0xfe, 0xe3, 0x42, 0xe3, 0x45, 0xc4,
	0x12, 0x45, 0x9e, 0x41, 0xd3, 0xec, 0x4a, 0xa4, 0x32, 0xea, 0x2b, 0xfb, 0x53, 0x6f, 0x7f, 0x68,
	0xd6, 0xad, 0x61, 0xb1, 0x6e, 0x0d, 0x4f, 0x71, 0xdd, 0x42, 0x67, 0xb3, 0x22, 0x55, 0x9d, 0x2b,
	0x6b, 0xd3, 0x56, 0xe7, 0xaf, 0xc0, 0x39, 0x63, 0x8a, 0xec, 0x57, 0xda, 0xd6, 0x6a, 0x8f, 0xea,
	0xdd, 0x7d, 0x4b, 0x6e, 0xa7, 0xc6, 0x13, 0x70, 0x71, 0x09, 0x22, 0x15, 0x83, 0xd2, 0x5a, 0xb4,
	0x35, 0xe1, 0x53, 0x70, 0x71, 0x47, 0xa9, 0x3a, 0x96, 0x16, 0xa2, 0x9e, 0xf7, 0xb6, 0xc2, 0xe6,
	0x3c, 0x85, 0x9d, 0x62, 0x32, 0x93, 0x7b, 0x95, 0xbe, 0x5c, 0x1d, 0xed, 0xbd, 0x8f, 0x37, 0x2b,
	0x57, 0x1b, 0x56, 0x43, 0xcf, 0x65, 0x52, 0xc9, 0x54, 0x1e, 0xd5, 0x5b, 0xc1, 0x3f, 0x01, 0x17,
	0x47, 0x75, 0x15, 0x7c, 0x69, 0x78, 0x6f, 0x75, 0x7c, 0x0e, 0x4d, 0x33, 0x76, 0xab, 0xdf, 0xa8,
	0x32, 0xd0, 0x7b, 0xbd, 0x4d, 0x2a, 0x0b, 0xfa, 0x05, 0xb4, 0x57, 0x03, 0x97, 0x54, 0xce, 0x77,
	0x7d, 0x0e, 0x6f, 0xc3, 0x70, 0x74, 0xf0, 0xeb, 0x83, 0xff, 0xf2, 0x0b, 0xf0, 0x6c, 0xf1, 0xe8,
	0x97, 0xff, 0x8d, 0x9b, 0xda, 0xf9, 0xf1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xc4, 0xd8,
	0x06, 0x36, 0x0c, 0x00, 0x00,
}
